title: A2-Android
email: your-email@example.com
description: >-
  A2-Android Project Website
baseurl: ""
url: "https://a2-android.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Minima settings
minima:
  skin: classic

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
