url: "https://a2-android.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Minima settings
minima:
  skin: classic

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
